[0.000000] (-) TimerEvent: {}
[0.000604] (-) JobUnselected: {'identifier': 'm_pubsub'}
[0.000695] (-) JobUnselected: {'identifier': 'move_turtle_pkg'}
[0.000733] (-) JobUnselected: {'identifier': 'test_interfaces'}
[0.000767] (-) JobUnselected: {'identifier': 'test_num'}
[0.000812] (test_para) JobQueued: {'identifier': 'test_para', 'dependencies': OrderedDict()}
[0.000857] (test_para) JobStarted: {'identifier': 'test_para'}
[0.088712] (-) TimerEvent: {}
[0.193907] (-) TimerEvent: {}
[0.296595] (-) TimerEvent: {}
[0.399410] (-) TimerEvent: {}
[0.503352] (-) TimerEvent: {}
[0.603787] (-) TimerEvent: {}
[0.704672] (-) TimerEvent: {}
[0.806405] (-) TimerEvent: {}
[0.907017] (-) TimerEvent: {}
[1.010575] (-) TimerEvent: {}
[1.113278] (-) TimerEvent: {}
[1.213744] (-) TimerEvent: {}
[1.314146] (-) TimerEvent: {}
[1.415501] (-) TimerEvent: {}
[1.519396] (-) TimerEvent: {}
[1.622989] (-) TimerEvent: {}
[1.727415] (-) TimerEvent: {}
[1.820446] (test_para) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_augmentation/ros_ament_python.py", line 57, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 281, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.8/subprocess.py", line 516, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', "import sys;from setuptools.extern.packaging.specifiers import SpecifierSet;from distutils.core import run_setup;dist = run_setup(    \'setup.py\', script_args=(\'--dry-run\',), stop_after=\'config\');skip_keys = (\'cmdclass\', \'distclass\', \'ext_modules\', \'metadata\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\'_\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\'metadata\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\'license_files\', \'provides_extras\')};sys.stdout.buffer.write(repr(data).encode(\'utf-8\'))"]\' returned non-zero exit status 1.\n'}
[1.821290] (test_para) JobEnded: {'identifier': 'test_para', 'rc': 1}
[1.822971] (-) EventReactorShutdown: {}
